### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by zurek11** [dengelke/node-zoom2#10]
I installed yaz from 
https://www.indexdata.com/resources/software/yaz/
Windows (64 bit) version and when I run it:
`npm i node-zoom2`
It throws error: 
`gyp: Call to 'yaz-config --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp`
any solutions?

**Comment by dengelke** [comment]
Unsure how setup yaz on windows, there is a guide here https://software.indexdata.com/yaz/doc/installation.win32.html but unsure how useful it would be

**Comment by gelks** [comment]
#19 should now resolve this issue, please use version 0.6.0
