### ISSUE TITLE
install on Ubuntu 20 + Node 16

### ISSUE THREAD

**Issue by andrisi** [dengelke/node-zoom2#15]
Trying to install on Ubuntu. Ran the preinstall.sh, yaz-client works ok, but the npm installation of node-zoom2 fails with some compilation issue when calling gyp. Perhaps a newer version of yaz then you expect. I included the logfile - perhaps it is obvious for you what fails. Let me know if I can help with anything. Thanks.
[2022-01-08T13_23_58_840Z-debug.log](https://github.com/dengelke/node-zoom2/files/7833285/2022-01-08T13_23_58_840Z-debug.log)

**Comment by dengelke** [comment]
Hey @andrisi thanks for the report and the log file, will investigate and let you know if I have any further queries. 

Only suggestion looking at this is to try downgrading to Node v12 to see if it resolves for now.

**Comment by dengelke** [comment]
@andrisi I have opened #16 but will take a bit more time to resolve some test errors, should be resolved shortly!

**Comment by dengelke** [comment]
@andrisi please use version 0.5.0 - this should resolve the problem. 

Please confirm and then I will close this issue.

**Comment by andrisi** [comment]
Yes, it works well. Thanks!

**Comment by andrisi** [comment]
fixed with https://github.com/dengelke/node-zoom2/issues/16
