### ISSUE TITLE
API results vs. yaz-client

### ISSUE THREAD

**Issue by andrisi** [dengelke/node-zoom2#20]
I'm looking into what is different between the API node-zoom2 uses and the yaz-client app. It seems that for the same query they give different results (success or 0) so there must be some difference between how they interpret or send the query or what options they set or not silently, or something else. I'm using `z3950.mokka.hu:2210` a national book catalog of Hungary and queries that search for first and last names of authors, like `f @attr 1=1 "Twain Mark"`. Over 1K results in yaz-client and 0 in node-zoom2. Optional commas or the order of names don't make any differenc in yaz-client.

**Comment by dengelke** [comment]
I've some digging, looks like they are using different commands firstly yaz-client uses
the following [c file](https://github.com/indexdata/yaz/blob/master/client/client.c) to send search queries like the `send_Z3950_searchRequest` function. Node-zoom2 uses commands like [ZOOM_query_prefix](https://software.indexdata.com/yaz/doc/zoom.query.html) which has a different implementation.

I can't see anything weird node-zoom2 is doing, would be interested to see if it could be replicated or not with some of the other zoom clients http://zoom.z3950.org/bind/index.html

**Comment by andrisi** [comment]
Thanks for investigating @dengelke. I added this issue to an Indexdata repo. Hope they'll know what's wrong.

**Comment by andrisi** [comment]
Someone suggested trying zoomsh, the ZOOM command line client, and with that it works as expected.

**Comment by dengelke** [comment]
I've tested #21 locally and gives the same number of 1693 results as the query on zoomsh locally - will release as 0.6.2

**Comment by dengelke** [comment]
@andrisi once you've checked please close this issue!

**Comment by andrisi** [comment]
works as expected

**Comment by dengelke** [comment]
Thanks for investigating @andrisi, that zoomsh find was great!
