### ISSUE TITLE
ResultSet.close() if zoom has it

### ISSUE THREAD

**Issue by andrisi** [dengelke/node-zoom2#23]
When working with large resultsets and calling getRecords() on the whole at once the node process is leaking memory and growing biger and bigger. Might not be directly related to retrieving results (I can send you my code privately) but maybe you can look into to. Not too important as this is a one off thing. Works great with usual resultsets.

**Comment by dengelke** [comment]
To match the rest of the API there is now a ResultSet.destroy() function which should have the desired functionality

**Comment by dengelke** [comment]
Closing issue for now, please use 0.7.2 or higher
