### ISSUE TITLE
preinstall.sh does not work on rpm based linux

### ISSUE THREAD

**Issue by uleodolter** [dengelke/node-zoom2#3]
there current version of preinstall.sh makes it impossibe to install node-zoom2 0.2.4 on Fedora, RedHat oder CentOS machines.

on Fedora Core 25 yaz is part of distribution ( dnf install -y libyaz-devel ).

but in general os package installation should be out of "npm install" scope,  maybe part of Dockerfile.

**Comment by dengelke** [comment]
Thanks for letting me know, should be fixed with #4 which was published in [0.2.5](https://github.com/dengelke/node-zoom2/releases/tag/0.2.5) please confirm and I'll close the issue

**Comment by uleodolter** [comment]
Thanks, that fixed the npm install problem.

But i got a lot of g++ compilation warnings on Fedora 25, that was the case in previous versions to, should i open an issue or try to create a patch?

**Comment by dengelke** [comment]
If you can create another issue with a log of the warnings that'd be great!
