### ISSUE TITLE
stream destroy problem

### ISSUE THREAD

**Issue by uleodolter** [dengelke/node-zoom2#6]
I wrote a very simple script based on examples/stream.js.  I works and i am getting records via sru, but before the script terminates i get the following error:

```
/home/ulrich/src/alma/sru-test/node_modules/node-zoom2/lib/read-stream.js:68
  state.destroyed = true;
                  ^

TypeError: Cannot set property 'destroyed' of undefined
    at ReadStream.stream.destroy (/home/ulrich/src/alma/sru-test/node_modules/node-zoom2/lib/read-stream.js:68:19)
    at ReadStream.stream._read (/home/ulrich/src/alma/sru-test/node_modules/node-zoom2/lib/read-stream.js:62:10)
    at ReadStream.stream._zoomReady (/home/ulrich/src/alma/sru-test/node_modules/node-zoom2/lib/read-stream.js:111:10)
    at ReadStream.<anonymous> (/home/ulrich/src/alma/sru-test/node_modules/node-zoom2/lib/read-stream.js:102:10)
```

**Comment by dengelke** [comment]
Give this a try

```var zoom = require('../lib');

zoom.connection('192.83.186.170:210/INNOPAC')
.set('preferredRecordSyntax', 'usmarc')
.query('prefix', '@attr 1=7 ' + '9780073383095')
.createReadStream()
.on('data', function (record) {
  var {json, xml, raw} = record
  console.log({json, xml, raw});
})
.on('close', function(close) {
  process.exit(1);
})```

Will update the examples in the meantime

**Comment by uleodolter** [comment]
Thanks, the `on('close' ...` seems to fix the problem.

In my case `record.syntax` is XML, is `record.json` intended to convert XML to JSON ?

**Comment by uleodolter** [comment]
Please look at the following example, it does not work because before marc4js.parse is called the close event calls exit(1) and terminates the node (i left out the connection details here). 

```
var sru = zoom.connection(
   ...
   createReadStream({ start: 0, limit: 10 });

var parser = marc4js.parse({ format: 'marcxml' });

sru.on('data', (record) => {
    marc4js.parse(record.xml, { format: 'marcxml' }, (err, records) => {
        marc4js.transform(records, { format: 'text' }, (err, output) => {
            console.log(output);
        });
   });
});

sru.on('close', (close) => {
    process.exit(1);
});
```

**Comment by dengelke** [comment]
The types are http://www.indexdata.com/yaz/doc/zoom.records.html

**Comment by uleodolter** [comment]
This example works perfect for all formats and you changed the code in read-stream.js the same way i did temporary for testing :+1:   

But for my datasource i get an error, because xml cannot converted to json, i think the reason for this must be the missing namespace `<record xmlns="">`.  INNOPAC returns the correct one `<record xmlns="http://www.loc.gov/MARC21/slim">`.

**Comment by dengelke** [comment]
Ok - good to know, can you find an example in an open z39.50 server that has the same issue?

**Comment by dengelke** [comment]
Will close this issue in the meantime though
