### ISSUE TITLE
Support libyaz4-dev

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [dengelke/node-zoom2#9]
Please add support for **libyaz4-dev** which the YAZ dev package available in Ubuntu LTS (16.04)

I had to changes this line in `binding.gyp` to make it work:
https://github.com/dengelke/node-zoom2/blob/1818b895a1ee4c636fe1fed5c53bcf7ff0db5d59/binding.gyp#L5

➡️

`yaz-config --libs --cflags`

**Comment by dengelke** [comment]
Thanks for this, will have to update the travis config to test against libyaz4-dev as well

If you have a look at preinstall.sh it'll install libyaz5-dev on Ubuntu 16.04 for you from the indexdata debian repository

**Comment by natlibfi-arlehiko** [comment]
> If you have a look at preinstall.sh it'll install libyaz5-dev on Ubuntu 16.04 for you from the indexdata debian repository

Ok. I think this should be documented in README. Although if the code doesn't explicitly depend on libyaz v5 it would be nice to prefer packages which are available in system repos?

**Comment by dengelke** [comment]
Yep, sure will make that change in the documentation. Agreed regarding dependencies, just want to make sure it's tested so I don't have to fix errors that exist only on libyaz4.

I'm unaware of any explicit dependencies but will need to run the test suite on it to make sure nothing is actually broken.

**Comment by dengelke** [comment]
I've now updated the documentation

**Comment by natlibfi-arlehiko** [comment]
The script won't help when installing directly with package.json. See #12
